### ISSUE TITLE
Unable to load existing wallet configuration from Caravan

### ISSUE THREAD

**Issue by Bosch-0** [Lily-Technologies/lily-wallet#15]
I downloaded my .json file wallet configuration from caravan and went attempting to load it into Lily I am prompted to enter a password (no password exists) - unsure if this is a viable way to load a wallet but would be great if this was possible.

**Comment by KayBeSee** [comment]
Interesting use case. It would nice to be able to add a vault to Lily from a Caravan config (we support creating Caravan configs from Lily but not the other way around).

The only issue with this is that Caravan doesn't keep track of device fingerprints which we need to sign transactions using HWI.

**Comment by Overtorment** [comment]
do we have testvectors for caravan..?

**Comment by KayBeSee** [comment]
What do you mean by testvectors? 

Do you mean tests for [`lilyConfigToCaravan`](https://github.com/Lily-Technologies/lily-wallet/blob/master/apps/frontend/src/utils/files.ts#L112) and [`caravanToLilyConfig`](https://github.com/Lily-Technologies/lily-wallet/blob/master/apps/frontend/src/utils/files.ts#L128) functions?

**Comment by Overtorment** [comment]
actual json files from caravan would be best

**Comment by KayBeSee** [comment]
Here is one with the xpubs redacted:

```
{
  "name": "Vault #1",
  "addressType": "P2SH",
  "network": "mainnet",
  "quorum": {
    "requiredSigners": 2,
    "totalSigners": 3
  },
  "startingAddressIndex": 0,
  "extendedPublicKeys": [
    {
      "name": "io",
      "xpub": "xpub420xxx69",
      "bip32Path": "m/45'/0/0/0",
      "xfp": "xxx"
    },
    {
      "name": "bluewater",
      "xpub": "xpub420xxx69",
      "bip32Path": "m/45'/0/0/0",
      "xfp": "xxx"
    },
    {
      "name": "Unknown",
      "xpub": "xpub420xxx69",
      "bip32Path": "Unknown",
      "xfp": "xxx"
    }
  ]
}
```

**Comment by Overtorment** [comment]
i took the liberty to fill xpubs:


```
{
  "name": "Vault #1",
  "addressType": "P2WSH",
  "network": "mainnet",
  "quorum": {
    "requiredSigners": 2,
    "totalSigners": 3
  },
  "startingAddressIndex": 0,
  "extendedPublicKeys": [
    {
      "name": "io",
      "xpub": "xpub6EJoguJn6okK6ymxkU53BZgjf4kqrL19uvTwqVnPRaV8qYvx1RhGtyKZxLhzY4YLCYtvB6DsGk1uR3GFBMvwgc5qz19WAxm2nSXZcoyNftY",
      "bip32Path": "m/48'/0'/0'/2'",
      "xfp": "A3909080"
    },
    {
      "name": "bluewater",
      "xpub": "xpub6FL52qF9cn2nL7T8gv6gStR8GcezKF4LgY53VLbi5sqRjc4PpBuYFp3nfep884hkuF9dC7KZ11mkthE1NVzbX98QmoJQqBFxQbHnpJ5vQKB",
      "bip32Path": "m/48'/0'/0'/2'",
      "xfp": "7AB71DF0"
    },
    {
      "name": "Unknown",
      "xpub": "xpub6ERjK6ubp5p7UUByXGadKvHcqEUMxvWPr7DkzqHz7GnnZEqdR9ffE3Y1DffYqRjJzeGWL1st1qH4kEaZCzjVnJoZ2PJUcnThi48D71zd6sJ",
      "bip32Path": "Unknown",
      "xfp": "F11B9FF2"
    }
  ]
}
```

wallets must agree that zero-index address on external hierarchy  is `bc1qtysquqsjqjfqvhd6l2h470hdgwhcahs4nq2ca49cyxftwjnjt9ssh8emel`

https://github.com/BlueWallet/BlueWallet/pull/5129
