### ISSUE TITLE
Error message when importing a file during multisig set up.

### ISSUE THREAD

**Issue by pedromvpg** [Lily-Technologies/lily-wallet#17]
If the json import fails because of file corruption or accidental file selection, there's no error message. Nice to have.

Does it support any other format besides .json? If not it could also state that to help users find the right file.

<img width="984" alt="Screen Shot 2020-08-22 at 10 47 01 PM" src="https://user-images.githubusercontent.com/807505/90969715-b8e81b80-e4c9-11ea-8fad-0fbfae73a5b3.png">

**Comment by KayBeSee** [comment]
Fixed in ea93c73deafd0723aafc51078aee50ce1781696b, 367f1cdbd73fa9b1728bf06baedafb790813e50f
