### ISSUE TITLE
Unconfirmed transaction label in recent activity in "send" screen

### ISSUE THREAD

**Issue by pedromvpg** [Lily-Technologies/lily-wallet#18]
Would be helpful to be able to differentiate unconfirmed transaction more clearly. 

<img width="1463" alt="Screen Shot 2020-08-22 at 11 02 27 PM" src="https://user-images.githubusercontent.com/807505/90970496-e934b780-e4d3-11ea-9443-3ac283d6a918.png">

**Comment by KayBeSee** [comment]
Recent activity has been removed from the send and receive screens.
