### ISSUE TITLE
Not detecting Ledger Nano S

### ISSUE THREAD

**Issue by starsoccer** [Lily-Technologies/lily-wallet#49]
When creating a new account I connect my Ledger Nano S, unlock it and select the bitcoin app. Lily Wallet does not seem to detect the device. 

It works fine with other devices like trezor though so seems to be specific to just the Ledger nano S

**Comment by KayBeSee** [comment]
Hey!

Do you know what firmware your Ledger is running? I have had a few folks reach out with a similar issue and I think it's due to an update in Ledger's firmware (see issue in HWI here: https://github.com/bitcoin-core/HWI/pull/403)

**Comment by starsoccer** [comment]
version 1.6.1

It might also be related to a chromium change that happened recently see my thread here for caravan that was also having an issue - https://github.com/unchained-capital/caravan/issues/182#issuecomment-738329113

**Comment by KayBeSee** [comment]
Interesting. I'll look into it more. 

I have a massive new release coming out in the next two weeks, so I'll make sure this fix is in there.
