### ISSUE TITLE
Unable to connect Trezor ONE

### ISSUE THREAD

**Issue by HardCorePawn** [Lily-Technologies/lily-wallet#6]
Tried to connect a Trezor ONE... get presented with "Open Bitcoin App on Device"... but Trezor does not use "apps"??!?

![Trezor Connected](https://i.imgur.com/EjooOhI.png)

Device never gets past the "logo screen", no PIN entry etc.

OS: Windows 10
lily-wallet version: 0.0.2-rc1.exe
Trezor: Latest firmware 1.9.2 (and latest Trezor Bridge)

**Comment by KayBeSee** [comment]
Good catch. The official v1 release that comes out tomorrow will include support for inputting your Pin. Thanks for this!

**Comment by HardCorePawn** [comment]
Have tested with 1.0.0.exe and the "connect wallet" and PIN entry shows up now, but still unable to connect as my Trezor is configured with "Passphrase" support. Unfortunately, this does not seem to be supported and after entering the PIN, the Trezor briefly displays "Enter Passphrase on Computer" screen before flicking back to Trezor Logo Screen. Lily-wallet then reverts to the "Click to Enter PIN" screen

**Comment by KayBeSee** [comment]
Ahh, interesting, I didn't know that feature existed but I just looked it up on Trezor's website.

It looks like HWI addresses this in https://github.com/bitcoin-core/HWI/issues/326 and https://github.com/bitcoin-core/HWI/issues/151

I'll add supporting Trezor passphrases to the roadmap.

**Comment by KayBeSee** [comment]
Ahh, interesting, I didn't know that feature existed but I just looked it up on Trezor's website.

It looks like HWI addresses this in bitcoin-core/HWI#326 and bitcoin-core/HWI#151

I'll add supporting Trezor passphrases to the roadmap.

**Comment by KayBeSee** [comment]
I believe this has been fixed.
